---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 2-demo-source-git-bb-app
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: 2-demo
  secretRef:
    name: bb-app-git-secret
  url: ssh://git@github.com/Fenigma/bb-app-source.git
